"use client";

import { useEffect, useRef } from "react";
import "./mgr.css";
import { wireColletPage, nonEmpty, fieldValue } from "./colletRuntime";

// Byte-faithful markup from the original managers.html (body), rendered
// server-side for SEO and hydrated with the original behavior via wireColletPage.
const HTML = `<header class="nav" id="nav">
  <div class="wrap nav-in">
    <a class="brand" href="#top" aria-label="Collet home">
      <svg width="28" height="28" viewBox="0 0 100 100" fill="none" aria-hidden="true">
        <circle cx="50" cy="50" r="30" stroke="var(--ink)" stroke-width="8" stroke-dasharray="49.8 13" stroke-linecap="round" transform="rotate(-90 50 50)"/>
        <polygon points="50,40 58.66,45 58.66,55 50,60 41.34,55 41.34,45" fill="var(--brass)"/>
      </svg>
      Collet
    </a>
    <a class="btn btn-brass" href="#waitlist">Book a demo</a>
  </div>
</header>

<main id="top">

  <section class="section hero">
    <div class="wrap hero-grid">
      <div>
        <span class="eyebrow r">For property managers &amp; agencies · Nigeria first</span>
        <h1 class="r">Sixty units. Fourteen owners. One month-end you <em>dread.</em></h1>
        <p class="lead r">Collet collects the rent, works out each owner’s share, and pays it out for you. You see where every payment went. So does the owner.</p>
        <a class="btn btn-brass btn-hero r" href="#waitlist">Book a demo</a>
      </div>

      <div class="hero-art r">
        <span class="glow" aria-hidden="true"></span>
        <div class="stmt" role="img" aria-label="An owner statement generated by Collet: rent collected ₦4,500,000, management fee ₦450,000, approved repairs ₦85,000, net remitted ₦3,965,000.">
          <div class="stmt-head">
            <div>
              <span class="who">Owner statement</span>
              <span class="per">MRS. F. ADEYEMI · 3 UNITS · JUN 2026</span>
            </div>
            <span class="seal" aria-hidden="true">
              <svg width="30" height="30" viewBox="0 0 100 100" fill="none">
                <circle class="ring" cx="50" cy="50" r="33" stroke="var(--brass)" stroke-width="9" stroke-dasharray="55.1 14" stroke-linecap="round" transform="rotate(-90 50 50)"/>
                <polygon points="50,38 60.39,44 60.39,56 50,62 39.61,56 39.61,44" fill="var(--brass)"/>
              </svg>
            </span>
          </div>
          <div class="stmt-row"><span class="lbl">Rent collected</span><span class="val">₦4,500,000</span></div>
          <div class="stmt-row neg"><span class="lbl">Management fee · 10%</span><span class="val">−₦450,000</span></div>
          <div class="stmt-row neg"><span class="lbl">Repairs · approved</span><span class="val">−₦85,000</span></div>
          <div class="stmt-net"><span class="lbl">Net remitted</span><span class="val">₦3,965,000</span></div>
          <span class="stmt-tag"><span class="dot"></span>PAID · 24 JUN · VIA AUTOSWEEP</span>
        </div>
      </div>
    </div>
  </section>

  <section class="section dark pain" id="pain">
    <div class="wrap">
      <span class="eyebrow r">Month-end, every month</span>
      <h2 class="r">Collecting the rent should be the easy part. In Nigeria, it’s a fight. And the accounting is worse.</h2>
      <div class="pain-grid r">
        <div class="pain-cell">
          <span class="tag">The chase</span>
          <h3>Who has actually paid?</h3>
          <p>Some pay late. Some pay half, then “next week.” Some go quiet till you show up at the gate. The chasing never stops.</p>
        </div>
        <div class="pain-cell">
          <span class="tag">The reconciliation</span>
          <h3>Then you match it all by hand.</h3>
          <p>Cash here, a transfer with no name on it there. You match every payment to a unit yourself, and the gaps hide in the pile.</p>
        </div>
        <div class="pain-cell">
          <span class="tag">The statements</span>
          <h3>Fourteen owners. Fourteen statements.</h3>
          <p>Rent in, your fee out, repairs out, what’s left owed. One owner at a time, line by line.</p>
        </div>
        <div class="pain-cell">
          <span class="tag">The payouts</span>
          <h3>Then you move money fourteen times.</h3>
          <p>Fourteen accounts, and you pray the maths held on every one.</p>
        </div>
      </div>

      <p class="pain-foot r">Winning owners is what grows your business. The chasing and the spreadsheet behind it are what eat your week. Quietly, 10 to 15 hours of it.</p>
    </div>
  </section>

  <section class="section mkt" id="market">
    <div class="wrap">
      <span class="eyebrow r">The market is moving</span>
      <h2 class="r">A booming market, held back by a spreadsheet.</h2>
      <p class="lead r">Nigerian real estate is now the country’s third-largest sector, and Abuja is where the new doors are going up. There are more owners every month. The one thing between you and five times the doors is how you keep the books.</p>

      <div class="stats r">
        <div class="stat">
          <div class="fig">₦41tn</div>
          <p class="cap">Nigeria’s real estate sector, now the 3rd largest in the economy.</p>
          <span class="src">NBS · 2025 GDP rebasing</span>
        </div>
        <div class="stat">
          <div class="fig">28M</div>
          <p class="cap">Unit housing deficit driving relentless rental demand.</p>
          <span class="src">Industry &amp; FG estimates</span>
        </div>
        <div class="stat">
          <div class="fig">230M+</div>
          <p class="cap">People, urbanising fast. Most city dwellers rent.</p>
          <span class="src">National population, 2025</span>
        </div>
        <div class="stat">
          <div class="fig">91%</div>
          <p class="cap">Of property managers plan to grow their portfolio.</p>
          <span class="src">Buildium · 2025 industry report</span>
        </div>
      </div>

      <p class="mkt-kick r">What works at 20 units breaks at 100 by hand. <b>Collet is how you grow past that ceiling.</b></p>
    </div>
  </section>

  <section class="section dark" id="how">
    <div class="wrap">
      <span class="eyebrow r">How Collet works</span>
      <h2 class="r">Run your whole book from one place.</h2>
      <div class="steps-grid">
        <div class="step r"><span class="num">01</span><h3>Bring your owners on</h3><p>Add each owner and their units. They sign a mandate. You set your fee. Add your agents too, and you control what they can do.</p></div>
        <div class="step r"><span class="num">02</span><h3>Rent matches itself</h3><p>Card, transfer, or cash you log. Every payment lands on the right unit and owner on its own. No more matching by hand.</p></div>
        <div class="step r"><span class="num">03</span><h3>Autosweep does the split</h3><p>It takes your fee, takes out repairs, and pays each owner what’s left. Automatically, with a statement for every owner.</p></div>
        <div class="step r"><span class="num">04</span><h3>See everything</h3><p>Every owner, every unit, every payout, and your own commission. Across the whole book, live.</p></div>
      </div>
    </div>
  </section>

  <section class="section feat" id="features">
    <div class="wrap">
      <span class="eyebrow r">What you get</span>
      <h2 class="r">The back office you’ve been running by hand.</h2>
      <div class="feat-grid">
        <div class="feat-item r"><span class="mk" aria-hidden="true"><svg width="16" height="16" viewBox="0 0 100 100"><circle cx="50" cy="50" r="36" fill="none" stroke="var(--brass)" stroke-width="11" stroke-dasharray="58 16" stroke-linecap="round" transform="rotate(-90 50 50)"/></svg></span><div><h3>One cockpit, every owner</h3><p>All your owners’ portfolios in a single view. Switch between them in a tap.</p></div></div>
        <div class="feat-item r"><span class="mk" aria-hidden="true"><svg width="16" height="16" viewBox="0 0 100 100"><circle cx="50" cy="50" r="36" fill="none" stroke="var(--brass)" stroke-width="11" stroke-dasharray="58 16" stroke-linecap="round" transform="rotate(-90 50 50)"/></svg></span><div><h3>Rent in one queue</h3><p>Collect across every unit by card, transfer, USSD, or recorded by you, auto-matched to the right lease.</p></div></div>
        <div class="feat-item r"><span class="mk" aria-hidden="true"><svg width="16" height="16" viewBox="0 0 100 100"><circle cx="50" cy="50" r="36" fill="none" stroke="var(--brass)" stroke-width="11" stroke-dasharray="58 16" stroke-linecap="round" transform="rotate(-90 50 50)"/></svg></span><div><h3>Reconciliation, automatic</h3><p>Payments match themselves to units and owners. Month-end stops being a manual hunt.</p></div></div>
        <div class="feat-item r"><span class="mk" aria-hidden="true"><svg width="16" height="16" viewBox="0 0 100 100"><circle cx="50" cy="50" r="36" fill="none" stroke="var(--brass)" stroke-width="11" stroke-dasharray="58 16" stroke-linecap="round" transform="rotate(-90 50 50)"/></svg></span><div><h3>Autosweep</h3><p>The moment rent lands, it splits to the landlord, you, and the agent automatically. Toggle it off and the full amount comes to you to disburse.</p></div></div>
        <div class="feat-item r"><span class="mk" aria-hidden="true"><svg width="16" height="16" viewBox="0 0 100 100"><circle cx="50" cy="50" r="36" fill="none" stroke="var(--brass)" stroke-width="11" stroke-dasharray="58 16" stroke-linecap="round" transform="rotate(-90 50 50)"/></svg></span><div><h3>Statements, generated</h3><p>Branded owner statements produced for you. The thing you sweat over, done in a click.</p></div></div>
        <div class="feat-item r"><span class="mk" aria-hidden="true"><svg width="16" height="16" viewBox="0 0 100 100"><circle cx="50" cy="50" r="36" fill="none" stroke="var(--brass)" stroke-width="11" stroke-dasharray="58 16" stroke-linecap="round" transform="rotate(-90 50 50)"/></svg></span><div><h3>Automatic reminders</h3><p>Collet nudges tenants before rent is due, by SMS, WhatsApp and email, so you stop chasing and rent comes in on time.</p></div></div>
        <div class="feat-item r"><span class="mk" aria-hidden="true"><svg width="16" height="16" viewBox="0 0 100 100"><circle cx="50" cy="50" r="36" fill="none" stroke="var(--brass)" stroke-width="11" stroke-dasharray="58 16" stroke-linecap="round" transform="rotate(-90 50 50)"/></svg></span><div><h3>Your commission, tracked</h3><p>What you’ve earned across every owner and let, finally in one number.</p></div></div>
        <div class="feat-item r"><span class="mk" aria-hidden="true"><svg width="16" height="16" viewBox="0 0 100 100"><circle cx="50" cy="50" r="36" fill="none" stroke="var(--brass)" stroke-width="11" stroke-dasharray="58 16" stroke-linecap="round" transform="rotate(-90 50 50)"/></svg></span><div><h3>Trust accounting, built in</h3><p>A double-entry ledger and a permanent audit trail. Every owner’s money accounted for to the kobo, and provable on demand.</p></div></div>
        <div class="feat-item r"><span class="mk" aria-hidden="true"><svg width="16" height="16" viewBox="0 0 100 100"><circle cx="50" cy="50" r="36" fill="none" stroke="var(--brass)" stroke-width="11" stroke-dasharray="58 16" stroke-linecap="round" transform="rotate(-90 50 50)"/></svg></span><div><h3>Your agents, in bounds</h3><p>Bring agents under your agency. They work within the limits you set, and everything they touch is logged.</p></div></div>
      </div>
    </div>
  </section>

  <section class="section win" id="trust">
    <div class="wrap win-in">
      <span class="eyebrow r">How you win owners</span>
      <h2 class="r">Every statement proves you’re straight. That’s how you grow your book.</h2>
      <p class="r">Most owners expect an agent to short them. So the manager who can show them exactly where their money went, the moment they ask, is the one who keeps the account and gets the referral. Collet gives you that proof without lifting a finger.</p>
    </div>
  </section>

  <section class="section cta" id="waitlist">
    <div class="wrap">
      <div class="cta-card r">
        <div>
          <span class="eyebrow">Founding agencies</span>
          <h2>Bring your whole book. Be first in the Abuja pilot.</h2>
          <p class="lead">Early access for managers and agencies. Founding agencies get hands-on setup, where we load your owners and units for you, plus founding terms that stay locked.</p>
          <p class="ll-bridge">Just a landlord, not a manager? <a href="/landlords">See Collet from the owner’s side&nbsp;→</a></p>
        </div>

        <div id="waitWrap">
          <form id="waitForm" novalidate>
            <div class="field">
              <label for="wAgency">Agency name</label>
              <input type="text" id="wAgency" name="agency" placeholder="Your agency" autocomplete="organization" />
            </div>
            <div class="field">
              <label for="wEmail">Work email</label>
              <input type="email" id="wEmail" name="email" placeholder="you@agency.com" required autocomplete="email" />
            </div>
            <div class="row2">
              <div class="field">
                <label for="wUnits">Units you manage</label>
                <select id="wUnits" name="units"><option value="">Select…</option><option>Under 20</option><option>20 to 50</option><option>50 to 150</option><option>150+</option></select>
              </div>
              <div class="field">
                <label for="wOwners">Owners you manage</label>
                <select id="wOwners" name="owners"><option value="">Select…</option><option>1 to 5</option><option>6 to 15</option><option>16 to 40</option><option>40+</option></select>
              </div>
            </div>
            <div class="field">
              <label for="wLoc">Where do you operate?</label>
              <input type="text" id="wLoc" name="location" placeholder="e.g. Maitama &amp; Wuse, Abuja" autocomplete="off" />
            </div>
            <div class="field">
              <label for="wTool">What do you use today?</label>
              <select id="wTool" name="current_tool"><option value="">Select…</option><option>Spreadsheets &amp; WhatsApp</option><option>Other property software</option><option>Nothing structured yet</option></select>
            </div>
            <button class="btn btn-brass" type="submit">Book a demo</button>
            <p class="form-note">We’ll only use this to reach you about the pilot.</p>
          </form>
          <div class="form-done" id="waitDone" role="status" tabindex="-1">
            <span class="mk" aria-hidden="true"><svg width="44" height="44" viewBox="0 0 100 100" fill="none"><circle cx="50" cy="50" r="33" stroke="var(--brass)" stroke-width="8" stroke-dasharray="55.1 14" stroke-linecap="round" transform="rotate(-90 50 50)"/><polygon points="50,38 60.39,44 60.39,56 50,62 39.61,56 39.61,44" fill="var(--brass)"/></svg></span>
            <h3>You’re on the list.</h3>
            <p>We’ll reach out before the Abuja pilot opens, and help you bring your book across.</p>
            <p class="done-cue">While you’re here · watch Collet in action</p>
            <div class="done-video" id="doneVideo"></div>
          </div>
        </div>
      </div>
    </div>
  </section>
</main>

<footer>
  <div class="wrap">
    <div class="foot-top">
      <div>
        <span class="foot-brand">
          <svg width="26" height="26" viewBox="0 0 100 100" fill="none" aria-hidden="true"><circle cx="50" cy="50" r="30" stroke="var(--bone)" stroke-width="8" stroke-dasharray="49.8 13" stroke-linecap="round" transform="rotate(-90 50 50)"/><polygon points="50,40 58.66,45 58.66,55 50,60 41.34,55 41.34,45" fill="var(--brass)"/></svg>
          Collet
        </span>
        <p class="foot-def">col·let &nbsp;·&nbsp; the precision grip that holds a part dead-centre, so it never slips. Every owner’s money, accounted for the same way.</p>
      </div>
      <p class="foot-mission">Bringing proof to Nigerian rent.</p>
    </div>
    <div class="foot-bottom">
      <span>Abuja, Nigeria · © 2026 Collet</span>
      <span><a href="#">Privacy</a> &nbsp;·&nbsp; <a href="#">Contact</a></span>
    </div>
  </div>
</footer>`;

export default function ManagersPage() {
  const ref = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const root = ref.current;
    if (!root) return;
    return wireColletPage(root, (r) =>
      nonEmpty({
        agency: fieldValue(r, "#wAgency"),
        units: fieldValue(r, "#wUnits"),
        owners: fieldValue(r, "#wOwners"),
        location: fieldValue(r, "#wLoc"),
        current_tool: fieldValue(r, "#wTool"),
        source: "managers",
      }),
    );
  }, []);

  return (
    <div className="mgr" ref={ref} dangerouslySetInnerHTML={{ __html: HTML }} />
  );
}
